### ISSUE TITLE
Empty sidebar when viewing photo in Photos

### ISSUE THREAD

**Issue by ollioddi** [nextcloud/photos#1447]
**Describe the bug**
When using the Photos app, there is no sidebar info for pictures.

Seeing the same photo in files, shows sidebar info.

Nextcloud 25.0.0
Photos 2.0.0

**To Reproduce**
1. Go to 'Photos'
2. Select a photo
3. Click on 'Open sidebar'
4. The sidebar is empty / blank.
![image](https://user-images.githubusercontent.com/7466744/199701663-ab437efa-1f47-4386-adca-e2ba729342c4.png)

**Expected behavior**
Sidebar info showing.
Screenshot from "Files" viewing the same file.
![image](https://user-images.githubusercontent.com/7466744/199701889-d44b10a2-ef3c-4382-8892-779c14ed1b91.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser Latest Edge and Firefox

**Browser log**
```
{
    "message": "Request failed with status code 404",
    "name": "AxiosError",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "requesttoken": "TOKEN"
        },
        "method": "propfind",
        "url": "https://ADRESS/remote.php/dav/files/USER/files/USER/Photos/2022/10/20221001_000000_5A1ACB5A.jpg",
        "data": "<?xml version=\"1.0\"?>\n\t\t\t<d:propfind  xmlns:d=\"DAV:\"\n\t\t\t\txmlns:oc=\"http://owncloud.org/ns\"\n\t\t\t\txmlns:nc=\"http://nextcloud.org/ns\"\n\t\t\t\txmlns:ocs=\"http://open-collaboration-services.org/ns\">\n\t\t\t<d:prop>\n\t\t\t\t<d:getlastmodified />\n\t\t\t\t<d:getetag />\n\t\t\t\t<d:getcontenttype />\n\t\t\t\t<d:resourcetype />\n\t\t\t\t<oc:fileid />\n\t\t\t\t<oc:permissions />\n\t\t\t\t<oc:size />\n\t\t\t\t<d:getcontentlength />\n\t\t\t\t<nc:has-preview />\n\t\t\t\t<nc:mount-type />\n\t\t\t\t<nc:is-encrypted />\n\t\t\t\t<ocs:share-permissions />\n\t\t\t\t<nc:share-attributes />\n\t\t\t\t<oc:tags />\n\t\t\t\t<oc:favorite />\n\t\t\t\t<oc:comments-unread />\n\t\t\t\t<oc:owner-id />\n\t\t\t\t<oc:owner-display-name />\n\t\t\t\t<oc:share-types />\n\t\t\t</d:prop>\n\t\t\t</d:propfind>"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 404
}

vue.runtime.esm.js:3019 
        
Error: AxiosError: Request failed with status code 404
    at Sidebar.vue:441:1
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.throw (runtime.js:119:21)
    at E (LegacyView.vue?a2e2:19:33)
    at a (LegacyView.vue?a2e2:19:33)

```

**Additional context**
Let me know if this issue is in the wrong repo. Seems like a "Sidebar" issue, but it only occurs in Photos.

**Comment by hansixxxx** [comment]
Same problem for me

**Comment by darguez** [comment]
Same problem here since 25.0.0

**Comment by ollioddi** [comment]
@szaimen The issue seems to be resolved and i am able to view sidebar from Photos.

**Comment by szaimen** [comment]
Great!
