### ISSUE TITLE
[Bug] Open sidebar fails for files with spaces in the file path

### ISSUE THREAD

**Issue by albgus** [nextcloud/photos#1489]
**Describe the bug**
The file details view fails to open for some photos and it seems to be related to folders with spaces in the filename.

Interestingly the error messages show that it's attempting to load `Camera%2520Roll`, which expands to `Camera%20Roll` (`%25` -> `%`), so it would seem that the URL is double encoded somewhere.

**To Reproduce**
1. Upload photos to the a folder with a space in the name, for instance "Camera roll"
2. Go to the photos viewer, open the photo and attempt to open sidebar for the context menu (...).
3. Nothing will happen / an empty sidebar will open in the gallery view.

**Expected behavior**
The sidebar should open with info about the photo.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 107

**Browser log**

<details>
<summary>Logs</summary>

```
[INFO] viewer: Opening viewer for fileInfo  {level: 1, app: 'viewer', uid: 'albin', fileInfo: {…}}
xhr.js:220          PROPFIND https://moln.online/remote.php/dav/files/user/Photos/Camera%2520Roll/2022/11/IMG_0415.jpg 404
(anonymous) @ xhr.js:220
e.exports @ xhr.js:16
e.exports @ dispatchRequest.js:56
d.request @ Axios.js:109
(anonymous) @ bind.js:9
(anonymous) @ FileInfo.js:29
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
j @ chunk loaded:1
s @ chunk loaded:1
(anonymous) @ chunk loaded:1
(anonymous) @ chunk loaded:1
A @ FileInfo.js:28
(anonymous) @ Sidebar.vue:422
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
E @ LegacyView.vue?a2e2:19
s @ LegacyView.vue?a2e2:19
(anonymous) @ LegacyView.vue?a2e2:19
(anonymous) @ LegacyView.vue?a2e2:19
open @ Sidebar.vue:412
(anonymous) @ Viewer.vue:905
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
Ng @ Pencil.vue?12b8:19
a @ Pencil.vue?12b8:19
(anonymous) @ Pencil.vue?12b8:19
(anonymous) @ Pencil.vue?12b8:19
showSidebar @ Viewer.vue:900
Lt @ vue.runtime.esm.js:3015
n @ vue.runtime.esm.js:1813
Lt @ vue.runtime.esm.js:3015
e.$emit @ vue.runtime.esm.js:3714
onClick @ NcActionButton.js:2
Lt @ vue.runtime.esm.js:3015
n @ vue.runtime.esm.js:1813
Kr.i._wrapper @ vue.runtime.esm.js:7458
Sidebar.vue:439 Error while loading the file data i {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
(anonymous) @ Sidebar.vue:439
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
E @ LegacyView.vue?a2e2:19
a @ LegacyView.vue?a2e2:19
Promise.then (async)
E @ LegacyView.vue?a2e2:19
s @ LegacyView.vue?a2e2:19
(anonymous) @ LegacyView.vue?a2e2:19
(anonymous) @ LegacyView.vue?a2e2:19
open @ Sidebar.vue:412
(anonymous) @ Viewer.vue:905
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
Ng @ Pencil.vue?12b8:19
a @ Pencil.vue?12b8:19
(anonymous) @ Pencil.vue?12b8:19
(anonymous) @ Pencil.vue?12b8:19
showSidebar @ Viewer.vue:900
Lt @ vue.runtime.esm.js:3015
n @ vue.runtime.esm.js:1813
Lt @ vue.runtime.esm.js:3015
e.$emit @ vue.runtime.esm.js:3714
onClick @ NcActionButton.js:2
Lt @ vue.runtime.esm.js:3015
n @ vue.runtime.esm.js:1813
Kr.i._wrapper @ vue.runtime.esm.js:7458
vue.runtime.esm.js:3047 Error: AxiosError: Request failed with status code 404
    at Sidebar.vue:441:1
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.throw (runtime.js:119:21)
    at E (LegacyView.vue?a2e2:19:33)
    at a (LegacyView.vue?a2e2:19:33)

```

</details>

**Additional context**
Seeing this request in the logs on the server side, and I'm also seeing other requests from the clients succeed so the 404 does not appear to be due to a nginx misconfiguration.

```
10.0.5.5 - - [20/Nov/2022:22:05:21 +0000] "PROPFIND /remote.php/dav/files/user/Photos/Camera%2520Roll/2022/11/IMG_0415.jpg HTTP/1.1" 404 215 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "10.0.0.100"
```

**Comment by szaimen** [comment]
Should be fixed with 25.0.2
