### ISSUE TITLE
Sharing album via public link: Image viewer requests user login

### ISSUE THREAD

**Issue by GitWidi** [nextcloud/photos#1526]
**Describe the bug**
When I try to view an image of a public shared album, a dialog box appears and I have to login with my account.

**To Reproduce**
1. Import some images to a folder of my Nextcloud account.
2. Launch the Photos app, view these images and ...
3. ... add these images to a newly created album.
4. Switch to the album view of this album, ...
5. ... open the sharing dialog (Add collaboratos),
6. ... click the button "Share via public link", 
7. ... click the modified button "Copy public link", and
8. ... close the dialog using button "Save".
9. Open a second web browser that does not have a Nextcloud account logged in. 
10. Paste the copied URL (clipboard) to the address bar, open the shared album, and view it.
11. Click on any of the images

**Expected behavior**
The image viewer should show this image.

**Screenshots**
Example, public link: https://cloud-test.fwidmann.net/apps/photos/public/7Z5wtC7ODReVOfxGTpcrFNfsnBZv1bzz
![grafik](https://user-images.githubusercontent.com/4623128/206751312-aa40aec0-9b6f-40dc-8cf9-062128837972.png)

**Server, Nextcloud**
 - Docker image (nextcloud:25.0.2-apache) on a cloud server of IONOS
 - NC 25.0.2
 - Photos V2.0.1

**Nextcloud Protocol**
***Reloading the shared album***
<html><body>

Level | App | Message |   | Time
-- | -- | -- | -- | --
Info | no app in context | IP  address throttled because it reached the attempts limit in the last 30  minutes [action: publicphotos_webdav_auth, delay: 400, ip:  89.244.253.162] |  | 2022-12-09T17:57:29+0100

</body>
</html>

***Other info message in the same context***
<html><body>

Level | App | Message |   | Time
-- | -- | -- | -- | --
Info | core | Bruteforce attempt from "89.244.253.162" detected for action "publicphotos_webdav_auth". |  | 2022-12-09T17:43:29+0100

</body>
</html>

**Desktop (please complete the following information):**
 - OS: Win 10 Enterprise 21H2
 - Browser: Firefox 107.0.1 (x64)

**Browser log**
```
﻿
7Z5wtC7ODReVOfxGTpcrFNfsnBZv1bzz:1 Refused to apply style from 'https://cloud-test.fwidmann.net/apps/photos/css/icons.css?v=47354877-7' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.4.0
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
index.js:19 Proxying an event bus of version 2.1.1 with 3.0.0
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ProxyBus.ts:11 Proxying an event bus of version 2.1.1 with 3.0.2
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
ConsoleLogger.js:60 [WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config 
{level: 0, app: 'viewer', ignoredMimes: Array(3)}
ConsoleLogger.js:56 [INFO] viewer: No OCA.Files app found, viewer is now in standalone mode 
{level: 0, app: 'viewer'}
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
index.esm.js:11 Proxying an event bus of version 2.1.1 with 3.0.2
viewer.js:63 Uncaught TypeError: Cannot read properties of undefined (reading 'fileActions')
    at viewer.js:63:13
    at viewer.js:65:2
    at viewer.js:65:2
index.js:19 Proxying an event bus of version 2.1.1 with 3.0.2
globals.js:60 oc_appswebroots is deprecated: use OC.appswebroots instead, this will be removed in Nextcloud 20
index.esm.js:11 Proxying an event bus of version 2.1.1 with 3.0.2
index.js:19 Proxying an event bus of version 2.1.1 with 3.0.2
index.esm.js:11 Proxying an event bus of version 2.1.1 with 3.0.2
ProxyBus.ts:16 Proxying an event bus of version 2.1.1 with 3.0.2
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
ProxyBus.ts:16 Proxying an event bus of version 2.1.1 with 3.0.2
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ConsoleLogger.js:56 [INFO] viewer: 6 viewer handlers registered 
{level: 0, app: 'viewer', handlers: Array(6)}
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
session-heartbeat.js:103 session heartbeat polling started
A bad HTTP response code (401) was received when fetching the script.
ConsoleLogger.js:64 [ERROR] photos: SW registration failed:  
{level: 0, app: 'photos', error: TypeError: Failed to register a ServiceWorker for scope ('https://cloud-test.fwidmann.net/apps/phot…}
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ConsoleLogger.js:56 [INFO] viewer: Opening viewer for fileInfo  
{level: 0, app: 'viewer', fileInfo: {…}}
null:1 
 GET https://cloud-test.fwidmann.net/apps/files_sharing/publicpreview/null?file=…1bzz/179497-IMG_20220819_193936_DRO.jpg&fileId=179497&x=1280&y=1024&a=true 404
Images.vue:263 Loading of file preview 179497-IMG_20220819_193936_DRO.jpg failed, falling back to original file
null:1 
 GET https://cloud-test.fwidmann.net/apps/files_sharing/publicpreview/null?file=…nBZv1bzz/179498-IMG_20220819_194021.jpg&fileId=179498&x=1280&y=1024&a=true 404
Images.vue:263 Loading of file preview 179498-IMG_20220819_194021.jpg failed, falling back to original file
null:1 
 GET https://cloud-test.fwidmann.net/apps/files_sharing/publicpreview/null?file=…1bzz/179499-IMG_20220819_193943_DRO.jpg&fileId=179499&x=1280&y=1024&a=true 404
Images.vue:263 Loading of file preview 179499-IMG_20220819_193943_DRO.jpg failed, falling back to original file
179499-IMG_20220819_193943_DRO.jpg:1 
 GET https://cloud-test.fwidmann.net/remote.php/dav//photospublic/7Z5wtC7ODReVOfxGTpcrFNfsnBZv1bzz/179499-IMG_20220819_193943_DRO.jpg 401
179498-IMG_20220819_194021.jpg:1 
 GET https://cloud-test.fwidmann.net/remote.php/dav//photospublic/7Z5wtC7ODReVOfxGTpcrFNfsnBZv1bzz/179498-IMG_20220819_194021.jpg 401
179497-IMG_20220819_193936_DRO.jpg:1 
 GET https://cloud-test.fwidmann.net/remote.php/dav//photospublic/7Z5wtC7ODReVOfxGTpcrFNfsnBZv1bzz/179497-IMG_20220819_193936_DRO.jpg 401
Mime.js:135 Error loading /photospublic/7Z5wtC7ODReVOfxGTpcrFNfsnBZv1bzz/179499-IMG_20220819_193943_DRO.jpg 
Event {isTrusted: true, type: 'error', target: img.viewer__file.viewer__file--active, currentTarget: img.viewer__file.viewer__file--active, eventPhase: 2, …}
Mime.js:135 Error loading /photospublic/7Z5wtC7ODReVOfxGTpcrFNfsnBZv1bzz/179498-IMG_20220819_194021.jpg 
Event {isTrusted: true, type: 'error', target: img.viewer__file--hidden.viewer__file, currentTarget: img.viewer__file--hidden.viewer__file, eventPhase: 2, …}
Mime.js:135 Error loading /photospublic/7Z5wtC7ODReVOfxGTpcrFNfsnBZv1bzz/179497-IMG_20220819_193936_DRO.jpg 
Event {isTrusted: true, type: 'error', target: img.viewer__file--hidden.viewer__file, currentTarget: img.viewer__file--hidden.viewer__file, eventPhase: 2, …}
```

**Additional context**

**Comment by pulsejet** [comment]
Duplicate of https://github.com/nextcloud/photos/issues/1452#issuecomment-1344186147

**Comment by joshtrichards** [comment]
@GitWidi Seems safe to close in favor of tracking progress in #1452. Can you close this Issue if you agree?
