### ISSUE TITLE
Unable to merge two entries in Photos 2.0, section People: Cannot read properties of undefined (reading 'faceDetections')

### ISSUE THREAD

**Issue by GuiPoM** [nextcloud/photos#1527]
**Describe the bug**
I am not able to merge two entries in Photos 2.0, section People.

**To Reproduce**
In Photos, section People, I select one entry (unamed, with a number) and I click on "..." then "Merge with different person".
Nothing happens. Screen becomes white. Only escape let me continue.

**Expected behavior**
I expect a dialog to appear

**Screenshots**
![image](https://user-images.githubusercontent.com/11942518/206812804-468b2654-e5b6-42bc-a2ba-a98b9fa71970.png)
![image](https://user-images.githubusercontent.com/11942518/206812822-122e5fc6-6713-4772-887b-484a0df139f6.png)

**Desktop (please complete the following information):**
 - OMV 6.1.1-1 (Shaitan) Linux 6.0.0-0.deb11.2-amd64 (Docker)
 - Chrome 108
 - 25.0.2
 - Photos 2.0.1

**Smartphone (please complete the following information):**

**Browser log**
```
TypeError: Cannot read properties of undefined (reading 'faceDetections')
    at FaceCoverMixin.js:50:72
    at Array.map (<anonymous>)
    at o.getFaceCover (FaceCoverMixin.js:50:6)
    at o.cover (FaceCover.vue:93:1)
    at e.get (vue.runtime.esm.js:3444:33)
    at e.evaluate (vue.runtime.esm.js:3545:27)
    at o.cover (vue.runtime.esm.js:5522:25)
    at o.coverDimensions (FaceCover.vue:97:1)
    at e.get (vue.runtime.esm.js:3444:33)
    at e.evaluate (vue.runtime.esm.js:3545:27)
Mt @ vue.runtime.esm.js:3047
```

**Additional context**
I am also using Recognize 3.3.0

**Comment by csware** [comment]
cf. issue #1505

**Comment by GuiPoM** [comment]
> cf. issue #1505

This is a technical issue, it crashes. It is not linked to any ergonomics here.

**Comment by csware** [comment]
Issue #1505 also reported on that javascript error.

**Comment by GuiPoM** [comment]
Yes, but I am not sure if the same error stack is reported. 

Here I want to emphasize that it never technically worked, it does not work, I am not able to merge one single entry, I only have issues. 

When the other issue is reported that it is complex to use. I would like to be in a situation where I can use it and find it complex, currently I can't. I don't know if there is anything I can do to debug more.
