### ISSUE TITLE
Photos in square/cropped view - setting not respected

### ISSUE THREAD

**Issue by loeffelpan** [nextcloud/photos#1573]
**Describe the bug**
Photos keep in square/cropped mode regardless of the setting in photos app.

**To Reproduce**
1. Go to photos.
2. See squared/cropped layout.
3. Click on Settings on the bottom left side and see, that squared/cropped layout is disabled by default.
4. Change the setting.
5. Nothing changes in the layout.

**Expected behavior**
Non-cropped layout should be default and setting should be respected.

**Screenshots**
![image](https://user-images.githubusercontent.com/34661317/210730977-10201a11-a3a4-416d-a236-279c80a7b651.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Version: 108 (latest)

**Browser log**
```
kbw3.duckdns.org/:1 
        
       Refused to apply style from 'https://kbw3.duckdns.org/apps/photos/css/icons.css?v=47354877-1' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
index.es.js:2337 
        
       Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
70903 @ index.es.js:3314
a @ bootstrap:19
71894 @ requesttoken.js:11
a @ bootstrap:19
22200 @ index.js:25
a @ bootstrap:19
70345 @ index.js:324
a @ bootstrap:19
(anonym) @ startup:4
a.O @ chunk loaded:25
(anonym) @ startup:5
(anonym) @ startup:5
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.4.0
index.es.js:2337 
        
       Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
70903 @ index.es.js:3314
i @ bootstrap:19
71894 @ requesttoken.js:11
i @ bootstrap:19
22200 @ index.js:25
i @ bootstrap:19
55058 @ LoggerBuilder.js:10
i @ bootstrap:19
17499 @ index.js:13
i @ bootstrap:19
85569 @ chunk loaded:1
i @ bootstrap:19
(anonym) @ startup:4
i.O @ chunk loaded:25
(anonym) @ startup:5
(anonym) @ startup:5
globals.js:60 
        
       jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
tn @ globals.js:60
get @ globals.js:91
(anonym) @ jquery.js:10853
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
38994 @ chunk loaded:1
r @ bootstrap:19
(anonym) @ startup:4
r.O @ chunk loaded:25
(anonym) @ startup:5
(anonym) @ startup:5
globals.js:60 
        
       $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
tn @ globals.js:60
get @ globals.js:91
(anonym) @ jquery.js:10856
(anonym) @ jquery.js:28
19755 @ jquery.js:14
r @ bootstrap:19
38994 @ chunk loaded:1
r @ bootstrap:19
(anonym) @ startup:4
r.O @ chunk loaded:25
(anonym) @ startup:5
(anonym) @ startup:5
index.es.js:2337 
        
       Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
70903 @ index.es.js:3314
r @ bootstrap:19
71894 @ requesttoken.js:11
r @ bootstrap:19
22200 @ index.js:25
r @ bootstrap:19
4820 @ index.js:14
r @ bootstrap:19
38994 @ chunk loaded:1
r @ bootstrap:19
(anonym) @ startup:4
r.O @ chunk loaded:25
(anonym) @ startup:5
(anonym) @ startup:5
index.es.js:2337 
        
       Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
70903 @ index.es.js:3314
i @ bootstrap:19
71894 @ requesttoken.js:11
i @ bootstrap:19
22200 @ index.js:25
i @ bootstrap:19
(anonym) @ Avatar.js:24
n @ Avatar.js:1
(anonym) @ Avatar.js:151
n @ Avatar.js:1
(anonym) @ Avatar.js:1
83507 @ Avatar.js:1
i @ bootstrap:19
1794 @ web.dom-collections.for-each.js:15
i @ bootstrap:19
80074 @ chunk loaded:1
i @ bootstrap:19
(anonym) @ startup:4
i.O @ chunk loaded:25
(anonym) @ startup:5
(anonym) @ startup:5
major.js:2 
        
       Proxying an event bus of version 2.1.1 with 1.3.0
e @ major.js:2
17331 @ web.dom-collections.for-each.js:15
i @ bootstrap:19
(anonym) @ Avatar.js:24
n @ Avatar.js:1
(anonym) @ Avatar.js:151
n @ Avatar.js:1
(anonym) @ Avatar.js:1
83507 @ Avatar.js:1
i @ bootstrap:19
1794 @ web.dom-collections.for-each.js:15
i @ bootstrap:19
80074 @ chunk loaded:1
i @ bootstrap:19
(anonym) @ startup:4
i.O @ chunk loaded:25
(anonym) @ startup:5
(anonym) @ startup:5
index.js:19 
        
       Proxying an event bus of version 2.1.1 with 3.0.0
e @ index.js:19
79862 @ index.js:71
i @ bootstrap:19
62021 @ index.js:5
i @ bootstrap:19
3607 @ NcAvatar.js:2
a @ NcAvatar.js:2
3351 @ NcAvatar.js:2
a @ NcAvatar.js:2
(anonym) @ NcAvatar.js:2
(anonym) @ NcAvatar.js:2
75925 @ NcAvatar.js:2
i @ bootstrap:19
80074 @ chunk loaded:1
i @ bootstrap:19
(anonym) @ startup:4
i.O @ chunk loaded:25
(anonym) @ startup:5
(anonym) @ startup:5
ProxyBus.ts:11 
        
       Proxying an event bus of version 2.1.1 with 3.0.2
e @ ProxyBus.ts:11
(anonym) @ ProxyBus.ts:59
(anonym) @ main.js:81
(anonym) @ main.js:81
index.es.js:2337 
        
       Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
8088 @ index.es.js:3314
r @ bootstrap:19
9517 @ requesttoken.js:11
r @ bootstrap:19
4273 @ index.js:25
r @ bootstrap:19
5058 @ LoggerBuilder.js:10
r @ bootstrap:19
7499 @ index.js:13
r @ bootstrap:19
(anonym) @ logger.js:25
(anonym) @ main.js:81
(anonym) @ main.js:81
ConsoleLogger.js:60 
        
       [WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config {level: '2', app: 'viewer', uid: 'admin', ignoredMimes: Array(2)}
value @ ConsoleLogger.js:60
value @ ConsoleLogger.js:86
(anonym) @ images.js:71
(anonym) @ main.js:81
(anonym) @ main.js:81
index.es.js:2337 
        
       Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
51499 @ index.es.js:3314
r @ bootstrap:19
21115 @ requesttoken.js:11
r @ bootstrap:19
62021 @ index.js:25
r @ bootstrap:19
3607 @ Avatar.js:2
a @ Avatar.js:2
3351 @ Avatar.js:2
a @ Avatar.js:2
(anonym) @ Avatar.js:2
(anonym) @ Avatar.js:2
28017 @ Avatar.js:2
r @ bootstrap:19
(anonym) @ Office.vue?66c9:1
(anonym) @ viewer.js:65
(anonym) @ viewer.js:65
index.esm.js:11 
        
       Proxying an event bus of version 2.1.1 with 3.0.2
e @ index.esm.js:11
(anonym) @ index.esm.js:59
(anonym) @ viewer.js:65
(anonym) @ viewer.js:65
viewer.js:63 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'registerAction')
    at viewer.js:63:25
    at viewer.js:65:2
    at viewer.js:65:2
(anonym) @ viewer.js:63
(anonym) @ viewer.js:65
(anonym) @ viewer.js:65
index.js:19 
        
       Proxying an event bus of version 2.1.1 with 3.0.2
e @ index.js:19
27594 @ index.js:71
a @ bootstrap:19
22200 @ index.js:5
a @ bootstrap:19
55058 @ LoggerBuilder.js:8
a @ bootstrap:19
17499 @ index.js:10
a @ bootstrap:19
52029 @ logger.js:3
a @ bootstrap:19
(anonym) @ ViewerComponent.vue?5c5f:20
(anonym) @ viewer.js:38
(anonym) @ viewer.js:38
globals.js:60 
        
       oc_appswebroots is deprecated: use OC.appswebroots instead, this will be removed in Nextcloud 20
tn @ globals.js:60
get @ globals.js:91
74411 @ mime.js:63
a @ bootstrap:19
(anonym) @ ViewerComponent.vue?5c5f:20
(anonym) @ viewer.js:38
(anonym) @ viewer.js:38
ProxyBus.ts:16 
        
       Proxying an event bus of version 2.1.1 with 3.0.2
e @ ProxyBus.ts:16
78595 @ index.ts:27
i @ bootstrap:19
45994 @ load script:2
i @ bootstrap:19
(anonym) @ jsonp chunk loading:86
(anonym) @ main.js:66
(anonym) @ main.js:66
index.es.js:2337 
        
       Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
58088 @ index.es.js:3314
i @ bootstrap:19
69517 @ requesttoken.js:11
i @ bootstrap:19
32341 @ index.js:25
i @ bootstrap:19
55058 @ LoggerBuilder.js:10
i @ bootstrap:19
17499 @ index.js:13
i @ bootstrap:19
6115 @ ncvuecomponents.js:2
a @ ncvuecomponents.js:2
9923 @ ncvuecomponents.js:2
a @ ncvuecomponents.js:2
5606 @ ncvuecomponents.js:2
a @ ncvuecomponents.js:2
5805 @ ncvuecomponents.js:2
a @ ncvuecomponents.js:2
(anonym) @ ncvuecomponents.js:2
(anonym) @ ncvuecomponents.js:2
33476 @ ncvuecomponents.js:2
i @ bootstrap:19
(anonym) @ Tag.vue?6116:19
(anonym) @ main.js:66
(anonym) @ main.js:66
ProxyBus.ts:16 
        
       Proxying an event bus of version 2.1.1 with 3.0.2
e @ ProxyBus.ts:16
74854 @ index.ts:27
i @ bootstrap:19
22200 @ index.js:5
i @ bootstrap:19
3607 @ ncvuecomponents.js:2
a @ ncvuecomponents.js:2
3351 @ ncvuecomponents.js:2
a @ ncvuecomponents.js:2
4208 @ ncvuecomponents.js:2
a @ ncvuecomponents.js:2
9446 @ ncvuecomponents.js:2
a @ ncvuecomponents.js:2
3432 @ ncvuecomponents.js:2
a @ ncvuecomponents.js:2
9923 @ ncvuecomponents.js:2
a @ ncvuecomponents.js:2
5606 @ ncvuecomponents.js:2
a @ ncvuecomponents.js:2
5805 @ ncvuecomponents.js:2
a @ ncvuecomponents.js:2
(anonym) @ ncvuecomponents.js:2
(anonym) @ ncvuecomponents.js:2
33476 @ ncvuecomponents.js:2
i @ bootstrap:19
(anonym) @ Tag.vue?6116:19
(anonym) @ main.js:66
(anonym) @ main.js:66
globals.js:60 
        
       jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
tn @ globals.js:60
get @ globals.js:91
(anonym) @ script.js?v=bc6bbbb9-1:492
globals.js:60 
        
       jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
tn @ globals.js:60
get @ globals.js:91
(anonym) @ files.js?v=bc6bbbb9-1:122
ProxyBus.ts:16 
        
       Proxying an event bus of version 2.1.1 with 3.0.2
e @ ProxyBus.ts:16
(anonym) @ index.ts:27
(anonym) @ main.js:37
(anonym) @ main.js:37
ProxyBus.ts:16 
        
       Proxying an event bus of version 2.1.1 with 3.0.2
e @ ProxyBus.ts:16
4854 @ index.ts:27
a @ bootstrap:19
2200 @ index.js:5
a @ bootstrap:19
3607 @ NcUserBubble.js:2
a @ NcUserBubble.js:2
3351 @ NcUserBubble.js:2
a @ NcUserBubble.js:2
4208 @ NcUserBubble.js:2
a @ NcUserBubble.js:2
(anonym) @ NcUserBubble.js:2
(anonym) @ NcUserBubble.js:2
6122 @ NcUserBubble.js:2
a @ bootstrap:19
(anonym) @ User.vue?vue&type=template&id=b064c4b8&scoped=true&:1
(anonym) @ main.js:37
(anonym) @ main.js:37
index.es.js:2337 
        
       Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
1099 @ index.es.js:3314
a @ bootstrap:19
6506 @ requesttoken.js:11
a @ bootstrap:19
3878 @ index.js:25
a @ bootstrap:19
395 @ index.js:14
a @ bootstrap:19
2534 @ index.js:41
a @ bootstrap:19
(anonym) @ notificationsService.js:67
(anonym) @ main.js:37
(anonym) @ main.js:37
globals.js:60 
        
       $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
tn @ globals.js:60
get @ globals.js:91
mounted @ NotificationsApp.vue:216
St @ vue.runtime.esm.js:2987
on @ vue.runtime.esm.js:4000
insert @ vue.runtime.esm.js:4391
L @ vue.runtime.esm.js:6897
Ha.nodeOps @ vue.runtime.esm.js:7108
e._update @ vue.runtime.esm.js:3734
r @ vue.runtime.esm.js:3844
e.get @ vue.runtime.esm.js:3415
e @ vue.runtime.esm.js:3405
e @ vue.runtime.esm.js:3861
Xn.$mount @ vue.runtime.esm.js:8727
e._init @ vue.runtime.esm.js:5656
Xn @ vue.runtime.esm.js:5717
(anonym) @ main.js:33
(anonym) @ main.js:37
(anonym) @ main.js:37
globals.js:60 
        
       $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
tn @ globals.js:60
get @ globals.js:91
mounted @ NotificationsApp.vue:221
St @ vue.runtime.esm.js:2987
on @ vue.runtime.esm.js:4000
insert @ vue.runtime.esm.js:4391
L @ vue.runtime.esm.js:6897
Ha.nodeOps @ vue.runtime.esm.js:7108
e._update @ vue.runtime.esm.js:3734
r @ vue.runtime.esm.js:3844
e.get @ vue.runtime.esm.js:3415
e @ vue.runtime.esm.js:3405
e @ vue.runtime.esm.js:3861
Xn.$mount @ vue.runtime.esm.js:8727
e._init @ vue.runtime.esm.js:5656
Xn @ vue.runtime.esm.js:5717
(anonym) @ main.js:33
(anonym) @ main.js:37
(anonym) @ main.js:37
globals.js:60 
        
       $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
tn @ globals.js:60
get @ globals.js:91
mounted @ NotificationsApp.vue:221
St @ vue.runtime.esm.js:2987
on @ vue.runtime.esm.js:4000
insert @ vue.runtime.esm.js:4391
L @ vue.runtime.esm.js:6897
Ha.nodeOps @ vue.runtime.esm.js:7108
e._update @ vue.runtime.esm.js:3734
r @ vue.runtime.esm.js:3844
e.get @ vue.runtime.esm.js:3415
e @ vue.runtime.esm.js:3405
e @ vue.runtime.esm.js:3861
Xn.$mount @ vue.runtime.esm.js:8727
e._init @ vue.runtime.esm.js:5656
Xn @ vue.runtime.esm.js:5717
(anonym) @ main.js:33
(anonym) @ main.js:37
(anonym) @ main.js:37
session-heartbeat.js:103 session heartbeat polling started
```

**Additional context**
Server is on 25.0.2 with Nextcloud-AIO and photos app is 2.0.1.

**Comment by Tirpitz93** [comment]
I would like to add I have the inverse issue: I cannot activate the squared view.

**Comment by simonspa** [comment]
Fixed by https://github.com/nextcloud/photos/pull/1659

**Comment by loeffelpan** [comment]
Not working for me with NC 26.0.0 RC2 😞
