### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'key')

### ISSUE THREAD

**Issue by DeanSabbah** [nextcloud/photos#2558]
**Describe the bug**
When entering the Unassigned faces in the photos/people tab, the console logs this error. I am using the Recognize app for facial recognition.

**To Reproduce**
While using the Recgnize app
1. Go to Photos
2. Click on People, then unassigned faces
3. See error

**Expected behavior**
I assume the pictures should load and I should be able to manually assign the faces

**Screenshots**
![image](https://github.com/user-attachments/assets/8796cec9-f4e3-4e52-96eb-0ef35cdf8b59)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Browser: Edge
 - Version of Edge: 126.0.2592.113

**Browser log**
```
TypeError: Cannot read properties of undefined (reading 'key')
    at ma (vue.runtime.esm.js:6466:15)
    at vue.runtime.esm.js:6844:25
    at w (vue.runtime.esm.js:6933:21)
    at vue.runtime.esm.js:6807:17
    at w (vue.runtime.esm.js:6933:21)
    at vue.runtime.esm.js:6807:17
    at w (vue.runtime.esm.js:6933:21)
    at ki.nodeOps [as __patch__] (vue.runtime.esm.js:7101:17)
    at e._update (vue.runtime.esm.js:3785:25)
    at o.r (vue.runtime.esm.js:3891:16)
```

**Comment by DeanSabbah** [comment]
If the Issue is with Recognize, I'll post an issue over there.

**Comment by ahook-hbs** [comment]
I am also receiving the same:
![Screenshot 2024-08-05 at 4 35 29 PM](https://github.com/user-attachments/assets/ea9bfc1b-d33f-4fbe-908e-4a6baa864266)


```
TypeError: Cannot read properties of undefined (reading 'key')
    at ma (vue.runtime.esm.js:6466:15)
    at vue.runtime.esm.js:6844:25
    at w (vue.runtime.esm.js:6933:21)
    at vue.runtime.esm.js:6807:17
    at w (vue.runtime.esm.js:6933:21)
    at vue.runtime.esm.js:6807:17
    at w (vue.runtime.esm.js:6933:21)
    at ki.nodeOps [as __patch__] (vue.runtime.esm.js:7101:17)
    at e._update (vue.runtime.esm.js:3785:25)
    at o.r (vue.runtime.esm.js:3891:16)
```

**Comment by hook-365** [comment]
I am receiving the same:
![Screenshot 2024-08-05 at 4 35 29 PM](https://github.com/user-attachments/assets/b7fe4ff8-3fff-4b2d-ac1f-298d1f655421)


```
TypeError: Cannot read properties of undefined (reading 'key')
    at ma (vue.runtime.esm.js:6466:15)
    at vue.runtime.esm.js:6844:25
    at w (vue.runtime.esm.js:6933:21)
    at vue.runtime.esm.js:6807:17
    at w (vue.runtime.esm.js:6933:21)
    at vue.runtime.esm.js:6807:17
    at w (vue.runtime.esm.js:6933:21)
    at ki.nodeOps [as __patch__] (vue.runtime.esm.js:7101:17)
    at e._update (vue.runtime.esm.js:3785:25)
    at o.r (vue.runtime.esm.js:3891:16)
```

**Comment by Permanently** [comment]
Also getting this. Seeming to find that unassigned faces are also not showing whatsoever, although I'm unsure whether this is a photos issue or a recognize issue.

**Comment by DeanSabbah** [comment]
I am almost certain that it is the photos app, as recognize works perfectly with the memories app.

**Comment by Permanently** [comment]
Good spot - just tried this myself. 100% the photos app.

**Comment by justwiebe** [comment]
For additional context, it looks like it happens in `VirtualScrolling.vue#updateScrollPosition` when you reach the bottom of the preloaded content
<img width="755" alt="image" src="https://github.com/user-attachments/assets/8f5a2d9d-dffc-4c77-9420-c661f33afced">

**Comment by justwiebe** [comment]
I don't know if this is related, but if I click on an image in "Unassigned Faces" to preview it, I get another `undefined` error:
<img width="677" alt="image" src="https://github.com/user-attachments/assets/d68d4483-4db0-4b91-ad4a-36f24d8fb3da">
<img width="780" alt="image" src="https://github.com/user-attachments/assets/3d2ff01c-4317-4feb-9f2e-7b5bbe26ff18">

**Comment by medivh-jay** [comment]
May I ask if this problem can be solved?

**Comment by target0dev** [comment]
Hello, I am facing this exact issue now. May I know if this is rectified?

I am using Photos Version 4.0.0-dev.1, Recognize Version 9.0.1, nextcloud version 31.0.3.
